version: "3.9"

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: resume-api
    restart: always
    # ports:
    #   - "8000:8000"
    networks:
      - application-network
    env_file:
      - ./api/.env.local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: resume-client
    restart: always
    # ports:
    #   - "3000:3000"
    networks:
      - application-network
    env_file:
      - ./client/.env.local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # gateway:
  #   build:
  #     context: gateway
  #     dockerfile: Dockerfile
  #   container_name: resume-gateway
  #   restart: always
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   networks:
  #     - application-network
  #   volumes:
  #     - /volumes/resume/cdn:/var/www/files
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

networks:
  application-network:
    external: true
