version: "3.9"

services:
  backend:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: resume-api
    restart: always
    networks:
      - application-network
    env_file:
      - ./api/.env.local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/base/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: resume-client
    restart: always
    networks:
      - application-network
    env_file:
      - ./client/.env.local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  application-network:
    external: true
