version: "3.9"

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: resume-api
    restart: always
    ports:
      - 8000
    networks:
      - application-network
    env_file:
      - ./api/.env.local

  client:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: resume-client
    restart: always
    ports:
      - 3000
    networks:
      - application-network
    env_file:
      - ./client/.env.local

  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    container_name: resume-gateway
    restart: always
    ports:
      - 443
      - 80
    networks:
      - application-network
    volumes:
      - /volumes/resume/cdn:/var/www/files

networks:
  application-network:
    external: true
